[package]
name = "lsp_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["macros", "io-std", "rt-multi-thread"] }
tower-lsp = "0.20.0"
